/**
 * This class is generated by jOOQ
 */
package com.artorias.database.jooq.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Post implements Serializable {

    private static final long serialVersionUID = 853845789;

    private Integer   postId;
    private String    title;
    private String    slug;
    private String    body;
    private Integer   authorId;
    private Timestamp createdOn;
    private Timestamp updatedOn;
    private Timestamp publishedOn;

    public Post() {}

    public Post(Post value) {
        this.postId = value.postId;
        this.title = value.title;
        this.slug = value.slug;
        this.body = value.body;
        this.authorId = value.authorId;
        this.createdOn = value.createdOn;
        this.updatedOn = value.updatedOn;
        this.publishedOn = value.publishedOn;
    }

    public Post(
        Integer   postId,
        String    title,
        String    slug,
        String    body,
        Integer   authorId,
        Timestamp createdOn,
        Timestamp updatedOn,
        Timestamp publishedOn
    ) {
        this.postId = postId;
        this.title = title;
        this.slug = slug;
        this.body = body;
        this.authorId = authorId;
        this.createdOn = createdOn;
        this.updatedOn = updatedOn;
        this.publishedOn = publishedOn;
    }

    public Integer getPostId() {
        return this.postId;
    }

    public Post setPostId(Integer postId) {
        this.postId = postId;
        return this;
    }

    public String getTitle() {
        return this.title;
    }

    public Post setTitle(String title) {
        this.title = title;
        return this;
    }

    public String getSlug() {
        return this.slug;
    }

    public Post setSlug(String slug) {
        this.slug = slug;
        return this;
    }

    public String getBody() {
        return this.body;
    }

    public Post setBody(String body) {
        this.body = body;
        return this;
    }

    public Integer getAuthorId() {
        return this.authorId;
    }

    public Post setAuthorId(Integer authorId) {
        this.authorId = authorId;
        return this;
    }

    public Timestamp getCreatedOn() {
        return this.createdOn;
    }

    public Post setCreatedOn(Timestamp createdOn) {
        this.createdOn = createdOn;
        return this;
    }

    public Timestamp getUpdatedOn() {
        return this.updatedOn;
    }

    public Post setUpdatedOn(Timestamp updatedOn) {
        this.updatedOn = updatedOn;
        return this;
    }

    public Timestamp getPublishedOn() {
        return this.publishedOn;
    }

    public Post setPublishedOn(Timestamp publishedOn) {
        this.publishedOn = publishedOn;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Post (");

        sb.append(postId);
        sb.append(", ").append(title);
        sb.append(", ").append(slug);
        sb.append(", ").append(body);
        sb.append(", ").append(authorId);
        sb.append(", ").append(createdOn);
        sb.append(", ").append(updatedOn);
        sb.append(", ").append(publishedOn);

        sb.append(")");
        return sb.toString();
    }
}
