/**
 * This class is generated by jOOQ
 */
package com.artorias.database.jooq.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Post implements Serializable {

    private static final long serialVersionUID = 843674901;

    private Integer   postId;
    private String    title;
    private String    slug;
    private String    body;
    private Integer   authorId;
    private Timestamp createdOn;
    private Timestamp updatedOn;
    private Timestamp publishedOn;

    public Post() {}

    public Post(Post value) {
        this.postId = value.postId;
        this.title = value.title;
        this.slug = value.slug;
        this.body = value.body;
        this.authorId = value.authorId;
        this.createdOn = value.createdOn;
        this.updatedOn = value.updatedOn;
        this.publishedOn = value.publishedOn;
    }

    public Post(
        Integer   postId,
        String    title,
        String    slug,
        String    body,
        Integer   authorId,
        Timestamp createdOn,
        Timestamp updatedOn,
        Timestamp publishedOn
    ) {
        this.postId = postId;
        this.title = title;
        this.slug = slug;
        this.body = body;
        this.authorId = authorId;
        this.createdOn = createdOn;
        this.updatedOn = updatedOn;
        this.publishedOn = publishedOn;
    }

    public Integer getPostId() {
        return this.postId;
    }

    public Post setPostId(Integer postId) {
        this.postId = postId;
        return this;
    }

    public String getTitle() {
        return this.title;
    }

    public Post setTitle(String title) {
        this.title = title;
        return this;
    }

    public String getSlug() {
        return this.slug;
    }

    public Post setSlug(String slug) {
        this.slug = slug;
        return this;
    }

    public String getBody() {
        return this.body;
    }

    public Post setBody(String body) {
        this.body = body;
        return this;
    }

    public Integer getAuthorId() {
        return this.authorId;
    }

    public Post setAuthorId(Integer authorId) {
        this.authorId = authorId;
        return this;
    }

    public Timestamp getCreatedOn() {
        return this.createdOn;
    }

    public Post setCreatedOn(Timestamp createdOn) {
        this.createdOn = createdOn;
        return this;
    }

    public Timestamp getUpdatedOn() {
        return this.updatedOn;
    }

    public Post setUpdatedOn(Timestamp updatedOn) {
        this.updatedOn = updatedOn;
        return this;
    }

    public Timestamp getPublishedOn() {
        return this.publishedOn;
    }

    public Post setPublishedOn(Timestamp publishedOn) {
        this.publishedOn = publishedOn;
        return this;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final Post other = (Post) obj;
        if (postId == null) {
            if (other.postId != null)
                return false;
        }
        else if (!postId.equals(other.postId))
            return false;
        if (title == null) {
            if (other.title != null)
                return false;
        }
        else if (!title.equals(other.title))
            return false;
        if (slug == null) {
            if (other.slug != null)
                return false;
        }
        else if (!slug.equals(other.slug))
            return false;
        if (body == null) {
            if (other.body != null)
                return false;
        }
        else if (!body.equals(other.body))
            return false;
        if (authorId == null) {
            if (other.authorId != null)
                return false;
        }
        else if (!authorId.equals(other.authorId))
            return false;
        if (createdOn == null) {
            if (other.createdOn != null)
                return false;
        }
        else if (!createdOn.equals(other.createdOn))
            return false;
        if (updatedOn == null) {
            if (other.updatedOn != null)
                return false;
        }
        else if (!updatedOn.equals(other.updatedOn))
            return false;
        if (publishedOn == null) {
            if (other.publishedOn != null)
                return false;
        }
        else if (!publishedOn.equals(other.publishedOn))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((postId == null) ? 0 : postId.hashCode());
        result = prime * result + ((title == null) ? 0 : title.hashCode());
        result = prime * result + ((slug == null) ? 0 : slug.hashCode());
        result = prime * result + ((body == null) ? 0 : body.hashCode());
        result = prime * result + ((authorId == null) ? 0 : authorId.hashCode());
        result = prime * result + ((createdOn == null) ? 0 : createdOn.hashCode());
        result = prime * result + ((updatedOn == null) ? 0 : updatedOn.hashCode());
        result = prime * result + ((publishedOn == null) ? 0 : publishedOn.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Post (");

        sb.append(postId);
        sb.append(", ").append(title);
        sb.append(", ").append(slug);
        sb.append(", ").append(body);
        sb.append(", ").append(authorId);
        sb.append(", ").append(createdOn);
        sb.append(", ").append(updatedOn);
        sb.append(", ").append(publishedOn);

        sb.append(")");
        return sb.toString();
    }
}
