/**
 * This class is generated by jOOQ
 */
package com.artorias.database.jooq.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Post implements Serializable {

    private static final long serialVersionUID = 334694798;

    private Integer   id;
    private String    title;
    private String    body;
    private Integer   author;
    private Timestamp createdOn;
    private Timestamp updatedOn;
    private Timestamp publishedOn;

    public Post() {}

    public Post(Post value) {
        this.id = value.id;
        this.title = value.title;
        this.body = value.body;
        this.author = value.author;
        this.createdOn = value.createdOn;
        this.updatedOn = value.updatedOn;
        this.publishedOn = value.publishedOn;
    }

    public Post(
        Integer   id,
        String    title,
        String    body,
        Integer   author,
        Timestamp createdOn,
        Timestamp updatedOn,
        Timestamp publishedOn
    ) {
        this.id = id;
        this.title = title;
        this.body = body;
        this.author = author;
        this.createdOn = createdOn;
        this.updatedOn = updatedOn;
        this.publishedOn = publishedOn;
    }

    public Integer getId() {
        return this.id;
    }

    public Post setId(Integer id) {
        this.id = id;
        return this;
    }

    public String getTitle() {
        return this.title;
    }

    public Post setTitle(String title) {
        this.title = title;
        return this;
    }

    public String getBody() {
        return this.body;
    }

    public Post setBody(String body) {
        this.body = body;
        return this;
    }

    public Integer getAuthor() {
        return this.author;
    }

    public Post setAuthor(Integer author) {
        this.author = author;
        return this;
    }

    public Timestamp getCreatedOn() {
        return this.createdOn;
    }

    public Post setCreatedOn(Timestamp createdOn) {
        this.createdOn = createdOn;
        return this;
    }

    public Timestamp getUpdatedOn() {
        return this.updatedOn;
    }

    public Post setUpdatedOn(Timestamp updatedOn) {
        this.updatedOn = updatedOn;
        return this;
    }

    public Timestamp getPublishedOn() {
        return this.publishedOn;
    }

    public Post setPublishedOn(Timestamp publishedOn) {
        this.publishedOn = publishedOn;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Post (");

        sb.append(id);
        sb.append(", ").append(title);
        sb.append(", ").append(body);
        sb.append(", ").append(author);
        sb.append(", ").append(createdOn);
        sb.append(", ").append(updatedOn);
        sb.append(", ").append(publishedOn);

        sb.append(")");
        return sb.toString();
    }
}
