language: java
jdk:
 - oraclejdk8
install: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
  - mvn test jacoco:report
after_success:
  - mvn coveralls:report
cache:
  directories:
  - .autoconf
  - $HOME/.m2
services:
  - postgresql
addons:
  postgresql: "9.5"
before_install:
 - sudo service postgresql restart
 - psql -c "CREATE DATABASE artorias" -U postgres && psql artorias < scripts/create_artorias_database.sql