language: java
jdk:
 - oraclejdk8
install: mvn flyway:migrate install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -Dartorias.env=test -Dspring.profiles.active=test
script:
  - mvn test jacoco:report -Dartorias.env=test -Dspring.profiles.active=test
after_success:
  - mvn coveralls:report -Dartorias.env=test -Dspring.profiles.active=test
services:
  - postgresql
addons:
  postgresql: "9.5"
before_install:
 - sudo service postgresql restart
 - psql -c "CREATE DATABASE artorias_test" -U postgres && psql artorias_test < scripts/create_artorias_test_database.sql
cache:
  directories:
  - $HOME/.m2
