language: java
jdk:
 - oraclejdk8
install: mvn -Dartorias.env=test flyway:migrate install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
  - mvn -Dartorias.env=test test jacoco:report
after_success:
  - mvn -Dartorias.env=test coveralls:report
services:
  - postgresql
addons:
  postgresql: "9.5"
before_install:
 - sudo service postgresql restart
 - psql -c "CREATE DATABASE artorias_test" -U postgres && psql artorias_test < scripts/create_artorias_test_database.sql
cache:
  directories:
  - $HOME/.m2
