/**
 * This class is generated by jOOQ
 */
package com.artorias.database.jooq;


import com.artorias.database.jooq.tables.Post;
import com.artorias.database.jooq.tables.records.PostRecord;

import javax.annotation.Generated;

import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling foreign key relationships between tables of the <code>blog</code> 
 * schema
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<PostRecord, Integer> IDENTITY_POST = Identities0.IDENTITY_POST;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<PostRecord> POST_PKEY = UniqueKeys0.POST_PKEY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 extends AbstractKeys {
        public static Identity<PostRecord, Integer> IDENTITY_POST = createIdentity(Post.POST, Post.POST.ID);
    }

    private static class UniqueKeys0 extends AbstractKeys {
        public static final UniqueKey<PostRecord> POST_PKEY = createUniqueKey(Post.POST, "post_pkey", Post.POST.ID);
    }
}
