/**
 * This class is generated by jOOQ
 */
package com.artorias.database.jooq;


import javax.annotation.Generated;

import org.jooq.Sequence;
import org.jooq.impl.SequenceImpl;


/**
 * Convenience access to all sequences in blog
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>blog.author_author_id_seq</code>
     */
    public static final Sequence<Long> AUTHOR_AUTHOR_ID_SEQ = new SequenceImpl<Long>("author_author_id_seq", Blog.BLOG, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>blog.post_post_id_seq</code>
     */
    public static final Sequence<Long> POST_POST_ID_SEQ = new SequenceImpl<Long>("post_post_id_seq", Blog.BLOG, org.jooq.impl.SQLDataType.BIGINT.nullable(false));
}
